class Commands:
    LEECH = "leech@jaatboy1bot"
    PURGE = "purge@jaatboy1bot"
    PAUSEALL = "pauseall@jaatboy1bot"
    RESUMEALL = "resumeall@jaatboy1bot"
    STATUS = "status@jaatboy1bot"
    SETTINGS = "settings@jaatboy1bot"
    EXEC = "exec@jaatboy1bot"
    UPLOAD = "upload@jaatboy1bot"
    YTDL = "ytdl@jaatboy1bot"
    PYTDL = "pytdl@jaatboy1bot"
    ABOUT = "about@jaatboy1bot"
    GETLOGS = "getlogs@jaatboy1bot"
    SERVER = "server@jaatboy1bot"
    USERSETTINGS = "usetting@jaatboy1bot"
    INSTADL = "instadl@jaatboy1bot"
